### ISSUE TITLE
Environment variables in configuration seetings seem not to work

### ISSUE THREAD

**Issue by hriekehof** [go2sh/cmake-integration-vscode#15]
Before i say anything thanks so much for your work. The multi root workspace is really a nice and the extension seems to work fine for me for know. However it seems to that when i define a cache variable with "cmake.cacheEntries" in the json file and use an evironment varibale in the definitions for path like "${env:Variable}\path\to\something" ${env:Variable} is not resolved in the CMakeCache.txt

It would be great if this would work

**Comment by go2sh** [comment]
Can you check with v0.4.0 I think i fixed it.

**Comment by hriekehof** [comment]
I have to say it again this extension is awesome :) 
I didn't check the old case but when i have an environment variable in the `cmake_configuration.json` like this:

```JSON
{
  "name": "RelWithDebInfo-M4",
  "buildType": "RelWithDebInfo",
  "toolchain": "c:/xxx/toolchain.cmake",
  "buildDirectory": "${env:BUILD_PATH}/project/${buildType}"
}
``` 

I get the following error message when i configure the project:

![image](https://user-images.githubusercontent.com/9348635/59094490-8844b200-8916-11e9-9cd9-feb43f7ef536.png)

The reason is clearly that the variable is not substituted

**Comment by go2sh** [comment]
Ah I see. Will investigate.

**Comment by go2sh** [comment]
I'll found it. Will push a tonight.

**Comment by hriekehof** [comment]
I tested this today again and i recognize that the variable substitution only works for the `buildDirectory` variable in the array. For the `toolchain` variable it seems not to work for me. It would be great if it would work for all variables in this file.
