### ISSUE TITLE
Doesn't find default_target in Makefile

### ISSUE THREAD

**Issue by johschmitz** [go2sh/cmake-integration-vscode#19]
This extension seems to be unable to find the default target. My CMake generated Makefile begins like this:

```
# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target
```
However the default target (all) is not available in the status bar menu of the extension.

**Comment by go2sh** [comment]
Yes, there is a special command for building all. Search for 'Build current project' to build all targets in a project.

**Comment by johschmitz** [comment]
Could that be added to the status bar selection as a special target so one
can execute it by pressing F7? Actually it should be some kind of default
when pressing F7 I think, because in most CMake projects one just calls a
simple make to build it.

Christoph Seitz <notifications@github.com> schrieb am Sa., 27. Apr. 2019,
10:58:

**Comment by go2sh** [comment]
Hey, I think about adding it. In the mean time, you can change your keybindigns or use `Shift + F7`, which is build all.

**Comment by go2sh** [comment]
I added the all target to the list in the status bar.
