### ISSUE TITLE
Error when compiling configurationProvider.ts

### ISSUE THREAD

**Issue by hriekehof** [go2sh/cmake-integration-vscode#20]
Hi again,

i tried to compile the beta version of this extension to try it out. But when i run ```npm run compile``` i get the following error message

![image](https://user-images.githubusercontent.com/9348635/58032640-52848880-7b23-11e9-92b9-06210a2bfc08.png)

i compiling an extension for the first time but it seems the error is in the code ?

**Comment by go2sh** [comment]
Hi, it is due to the new TS version. I have a fix for that. Will push tonight with the docs.

**Comment by hriekehof** [comment]
Man it would be so great if you could push a fix or new version :) With VSCode 1.35 CMake-Tools broke for all my projects. If i don't find anything else i have to switch back to eclipse ...

**Comment by go2sh** [comment]
Ah, sorry. I'am currently at home having Elternzeit. So spare time is very little. ;-) I pushed all my fixes also into the market place.

Chears.
