### ISSUE TITLE
Unable to build project

### ISSUE THREAD

**Issue by DavidA2014** [go2sh/cmake-integration-vscode#22]
I have VS Code 1.35.0 and CMake Integration 0.4.1, running on Windows 10.

I have created a workspace and added to it a folder containing:

- CMakeLists.txt
- CMakeSettings.json

Hitting F7 does nothing.  Nothing is reported by the extension in the status bar or in the output window. I guess I have omitted some basic step. Please will you suggest what I need to do to make CMake work with this project?

**Comment by go2sh** [comment]
Did you set a generator in the settings? I guess you want visual studio. Set it and try to restart.
Can you check, if there is a cmake tab under the outputs? Can you post it.

**Comment by DavidA2014** [comment]
The generator for the workspace is Ninja (the default).

I have a cmake tab but it has no output:

![image](https://user-images.githubusercontent.com/7724321/59195762-ae6f8980-8b84-11e9-9f2c-197f993682f6.png)

I get some errors at startup:

![image](https://user-images.githubusercontent.com/7724321/59195847-f1316180-8b84-11e9-869c-8bbc3cec00d9.png)

Do I need to install CMake?

**Comment by DavidA2014** [comment]
I have now installed CMake 3.15 and set the generator to Visual Studio 15 2017.
When starting VS Code I see:
![image](https://user-images.githubusercontent.com/7724321/59196507-ce07b180-8b86-11e9-893f-8a7088a0ccfa.png)

**Comment by go2sh** [comment]
Can post the complete error. I'll add a check about cmake and its version

**Comment by DavidA2014** [comment]
Complete error:
`Failed to start CMake Client(c:\SVNProj\<snip>\Prototypes\CPlaneTest): Failed to activate protocol version: "CMAKE_GENERATOR" is set but incompatible with configured generator value.`

**Comment by go2sh** [comment]
Ah yes. Search for restart client in commands an delete the build Folder before. Check the docs under troubleshooting

**Comment by DavidA2014** [comment]
Thanks that fixed it.

Is the build output shown in OUTPUT > Extensions >CMake ?

FYI I see this warning in the console:
`CMake Deprecation Warning:
  The 'cmake-server(7)' is deprecated.  Please port clients to use the
  'cmake-file-api(7)' instead.`

**Comment by go2sh** [comment]
The configure and build output is shown under Output > CMake - FolderName. See your image above.

I know, that it is deprecated. The extension supports the file api already. You can change it in the settings. 

I'll add some kind of cmake detection and version detection in the next release.

**Comment by DavidA2014** [comment]
Thank you for your help. It's working nicely now.

**Comment by go2sh** [comment]
You are welcome.
