### ISSUE TITLE
Configure workspace/folder commands are not prefixed with cmake

### ISSUE THREAD

**Issue by hriekehof** [go2sh/cmake-integration-vscode#26]
In the Shortcut overview i see that the commands to configure a workspace or a folder are not prefixed with CMake.

![image](https://user-images.githubusercontent.com/9348635/59275168-147b1000-8c5c-11e9-9b32-99aafafef146.png)

It would be nice to have the same prefix there to be sure that with the Configure means a CMake configure.

**Comment by mmanyen** [comment]
I have updated package.json for this change. 

I completely noob to github, so I don't know how to create a branch/pull request so I attach the changed file here...

[package.zip](https://github.com/go2sh/cmake-integration-vscode/files/3278137/package.zip)

**Comment by go2sh** [comment]
Ah. Initially, I thought it would be nice to prefix the operations with the area they are used for, e.g. `Build`  for build related tasks, `Configure` -> for configure related task, etc.
But I don't mind. Do you think it would be better with everything having the `CMake` prefix? @mmanyen @hriekehof

**Comment by hriekehof** [comment]
personally i would prefer to prefix all commands with `CMake`. In VScode you can end up with alot of different extensions which all introduce their commands etc. And `Configure` for example is surely something which occurs often.

Another thing is that i use the command mode with `strg + shift + p` alot. When i then search for CMake i find all commands which are possible to use and i'm also sure that they belong to CMake. When i search for `Configure` i also find other configure commands from other extensions and have to read more lines to be sure to select the CMake configure project folder.

But as i said this is surly a matter of taste but i would prefer a prefix for all available commands

**Comment by mmanyen** [comment]
I have been running with the above change and prefer it greatly.

**Comment by go2sh** [comment]
I'll change it. :-)
