### ISSUE TITLE
Extra generator seems not to work 

### ISSUE THREAD

**Issue by hriekehof** [go2sh/cmake-integration-vscode#28]
I recognized that the extra generator is not working. I recently wanted to double check something in eclipse but the `.project` and `.cproject` are missing in the build folder.
I have configured `Eclipse CDT4` as an extra generator. I am sure i saw the files already once but since i setup everything new with version 0.4.1 the eclipse files seem not to be generated

**Comment by go2sh** [comment]
Hm, I did a quick check. I changed the extraGenerator in the settings and restart the CMake Client. The build folder contained the `.project` and `.cproject` files. So can't really reproduce.

**Comment by hriekehof** [comment]
Hm strange. I double checked again today. I configured the extra generator in the project folder settings and restarted the CMake client for this folder. I also reconfigured the project but the `.cproject` and `.project` files are not showing up.
This is on Windows 10 1809. But its not a big issue

**Comment by go2sh** [comment]
Can you check that with the new 0.5.0 version? I try to reproduce it under windows.

**Comment by hriekehof** [comment]
On my machine its still not working. I deleted the build folder i did a complete reconfigure. Building with ninja works fine but the .cproject file from the extra generator are still missing. Can i find some logging information somewhere ?

**Comment by go2sh** [comment]
Had a little bug fixing run.
