### ISSUE TITLE
Win10 and VS2019

### ISSUE THREAD

**Issue by mmanyen** [go2sh/cmake-integration-vscode#31]
VS 2019 does not appear as an option for generation. 

My CMake says it does, and it works great from command line

There seems to be more than this going on. With only this extension and the MS C++ extension running there are no options for cmake. Selecting CMake: Select CMake config brings up an empty selector. CMake: Restart CMake does nothing at all.

**Comment by go2sh** [comment]
I added VS19 to the config.
For the later part: I cannot reproduce your error. Can you post a screenshot or some thing similar to reproduce?

**Comment by go2sh** [comment]
Can you open a new issue for your other bug with the extension?
