### ISSUE TITLE
Does not work with cmake 3.15

### ISSUE THREAD

**Issue by barcharcraz** [go2sh/cmake-integration-vscode#33]
cmake 3.15 removed the cmake server api and replaced it with the cmake file api (I have no real idea why)

**Comment by go2sh** [comment]
In the settings, you can choose between server and file api already. I'll add auto-detection in the next release.

**Comment by barcharcraz** [comment]
Consider updating the description of the plugin to mention that.

**Comment by go2sh** [comment]
I wasn't aware of the fact that they removed the server support. It is still part of the docs. :-_
