### ISSUE TITLE
Variable substitution does not work in all cases in cmake_configurations

### ISSUE THREAD

**Issue by hriekehof** [go2sh/cmake-integration-vscode#35]
I tried using variable substitution of environment variables in the `cmake_configurations.json`
For the `buildDirectory` i can use something like 

`cmake.buildDirectory:${env:BUILD_PATH}/project/${buildType}`

But when i want to use an environment variable for the `toolchain` variable to specify a toolchain file it seems not to work. Would be great to use environment variables also for the toolchain file

**Comment by go2sh** [comment]
Added. :)
