### ISSUE TITLE
the reconfigure on change  can not always working

### ISSUE THREAD

**Issue by Raysuner** [go2sh/cmake-integration-vscode#38]
hi，I met some problems with the extension

cmake version: 3.10.2              

 extension version: 0.61

I have selected the "Reconfigure on change" and "Auto save" options, but when I change the CMakeLists.txt file from right to error, the extension will reconfigure. In turn，it does not work

for example
```cmake
cmake_minimum_required(VERSION 3.10.2)

project(Learning)

set(CMAKE_CXX_STANDARD 14)

add_executable(Learning src/main.cpp)
```

I remove "src" that in CMakeLists.txt, it will create a red underline below fouth row. when I add the "src" at same position, it has no effect. I must using the command of "configure current project" if i want to reconfigure the project.

Am I clear?

**Comment by go2sh** [comment]
Are you using the server backend? The cmake server code for change detection is quite buggy. I'll have to come up with some VSCode based solution. In the meantime you can just hit build (F7) and CMake on build will detect, if the CMake source has changed. I hope that helps.

**Comment by Raysuner** [comment]
Thanks a lot. It's not that bad，I can accept it.
