### ISSUE TITLE
Many include folders not found.

### ISSUE THREAD

**Issue by SoftwareApe** [go2sh/cmake-integration-vscode#39]
Thank you for creating this extension, it's quite helpful in configuring complex CMake workspaces.

ROS/catkin use CMake under the hood. Maybe it's something about the structure of the CMakeLists that makes it hard to find some includes.

3 examples where the includes weren't added to the include directories:

1. Maybe it's the comment? Or maybe the macro expansion (quite common with catkin):

```
include_directories(
    include
    src
    # ${HEADERS}
    ${catkin_INCLUDE_DIRS}
)
```

2. Here I can only blame the macro expansion, otherwise it seems straightforward
```
include_directories(
    inc
    ${catkin_INCLUDE_DIRS}
)
```

3. I guess target_include_directories may be a bit more of an edge case than the previous two:
```
target_include_directories(stubbing
    PUBLIC ${CMAKE_CURRENT_LIST_DIR}/inc
    PUBLIC ${CMAKE_CURRENT_LIST_DIR}/src
    PUBLIC ${CMAKE_CURRENT_LIST_DIR}/
)
```

None of the include directories here are added to the path. I can only guess that this is a problem parsing the CMakeLists.txt.

**Comment by go2sh** [comment]
Can you eleborate more on the problem you encounter with the extension? Is it the cpptools support? Or do you have problems building?
The extension doesn't parse the cmake files on its own. It relays on either the cmake-server or the cmake-file api to provide all necessary information to it.

**Comment by SoftwareApe** [comment]
Thank you for your quick reply 👍 . I thought the extension scans directly, I did take a quick look at the code but not deep enough to find how the scan for dependencies works.

Do you have any idea why it might find some dependencies but not others? It finds about half of my projects dependencies, but not all of them and adds them to cpptools.

**Comment by go2sh** [comment]
Is this still a problem?

**Comment by SoftwareApe** [comment]
I think this is a problem with cmake

Christoph Seitz <notifications@github.com> schrieb am Mi., 11. Sep. 2019,
21:31:

**Comment by go2sh** [comment]
Any news? Feel free to open it again.

**Comment by SoftwareApe** [comment]
Sorry, I was on vacation. I didn't check anymore.
