### ISSUE TITLE
Insiders: Failed to start CMake(...): Failed to activate protocol version: "CMAKE_GENERATOR"

### ISSUE THREAD

**Issue by atar-axis** [go2sh/cmake-integration-vscode#4]
Hi there, I installed the vscode-insiders version yesterday and unfortunately I am getting the following error message now:

`Failed to start CMake(ff1_selfcheck): Failed to activate protocol version: "CMAKE_GENERATOR" is set but incompatible with configured generator value.`

Is this a bug or a configuration problem?

similar problem found on the internetz: https://github.com/vector-of-bool/vscode-cmake-tools/issues/163

**Comment by atar-axis** [comment]
Btw, the problem is not showing up if I remove `"cmake.generator": "Unix Makefiles"`

**Comment by atar-axis** [comment]
`Restart CMake Client (Clean)` fixed it :grin:

**Comment by go2sh** [comment]
I need to write some more documentation.^^

**Comment by atar-axis** [comment]
It is in fact one of the pitfalls on your README, I would say it is my fault hence :grin:
