### ISSUE TITLE
package-lock.json not commited

### ISSUE THREAD

**Issue by SoftwareApe** [go2sh/cmake-integration-vscode#40]
Running npm install shows a warning that `package-lock.json` should be committed. This way every developer has the same dependency tree.

https://stackoverflow.com/a/44210813/3387223

**Comment by go2sh** [comment]
I can do that. Personally, I use yarn, so only the yarn lock file is committed right now. ;-)

**Comment by SoftwareApe** [comment]
Ah, didn't notice that, sorry!

**Comment by go2sh** [comment]
I'll use yarn for most of my projects so I'll keep it that way and close this issue. I do not know any way to keep both in sync. But I'll create a CONTRIBUTING.md file with the required steps for developers. I hope it's okay that way for you.
