### ISSUE TITLE
Build stops after ~70 files compiled

### ISSUE THREAD

**Issue by rudx0029** [go2sh/cmake-integration-vscode#43]
Ubuntu Linux 16.04
VSCode 1.37.1
CMake Integration 0.6.3

When triggering a build with multiple work spaces, the build will stop after compiling around 70 files. I will re-start the build via the GUI button or `F7` but the build will again stop after 70 files are compiled.

We have a large environment spreading across 6 architectures and building 5000+ objects per architecture.

Unfortunately I can not provide logs.

**Comment by go2sh** [comment]
Can you give me some time span? Or is it always after some amount of files? Does the cmake process get killed or is it alive afterwards and just the vscode output stops? There is also some problems with cmake, that it needs some time to flush some output on stdout.

**Comment by mmanyen** [comment]
This was also a recurring problem in the vector-of-bool extension.

**Comment by rudx0029** [comment]
> Can you give me some time span? Or is it always after some amount of files? Does the cmake process get killed or is it alive afterwards and just the vscode output stops? There is also some problems with cmake, that it needs some time to flush some output on stdout.

Thanks for the response! Let me try and build up some characterization for this. I rebooted my machine and the problem hasn't manifested, yet.  Our build is running 16GB+ in RAM and between VSCode, we may be experiencing resource issues.  Again, I'll try and capture these details over time. I think the only course of action would be to provide some feedback if the process failed unexpectedly - log statement or something simple.

**Comment by go2sh** [comment]
See #46 :) New version is out.
