### ISSUE TITLE
Build output stops after ~27000 lines

### ISSUE THREAD

**Issue by garbotron** [go2sh/cmake-integration-vscode#46]
When building a target that produces a large amount of text in the output panel, the build stops after ~27000 lines have been printed. It appears that the build process is terminated, though that is unclear.

Tested on Ubuntu 18.04 using standard Unix tools (make, gcc, etc).

You can test it with a CMakeLists.txt file that looks like this:
```
cmake_minimum_required(VERSION 3.5 FATAL_ERROR)
project(test)

foreach(x RANGE 0 100000)
  message("x=${x}")
endforeach()
```

After the project is loaded, save the CMakeLists.txt file to invalidate it, then build the current target. The output should look like this:
```
x=0
x=1
...
x=27098
x=27099
```

**Comment by go2sh** [comment]
Hm, sounds similar to the other issue with a large project. I suspect the node child process api to kill the process due to the buffer limit reached. I'll try to test it with your example.

**Comment by go2sh** [comment]
It was, what I expected. The execFile command has a 1MB buffer, when its full the command gets killed. It is recommended to use spawn instead.
