### ISSUE TITLE
Version string not found in output

### ISSUE THREAD

**Issue by DeltaTee97** [go2sh/cmake-integration-vscode#50]
When trying to start using cmake-integration, I get the error:

    Failed to start CMake Client(<reponame>): Version string not found in output.

I could not find this in the documentation and am unsure how to check what is actually wrong with the setup. I am trying to use cmake-integration for remote compiling.

I don't see any special setup I had to do with cmake-tools, which I am attempting to switch away from for the multiroot capability.

**Comment by go2sh** [comment]
Hey there sorry for the late response. There migh be some thing wrong with your `cmakePath` specefied. The extension checks the version of cmake for certain features. Can you try to run `cmake --version` on your target computer? (If you have the cmake path set, use that path and add the `--version`) Can you post your output?

**Comment by DeltaTee97** [comment]
The cmake version output on the target computer is:

    > cmake --version
    cmake3 version 3.13.4
    
    CMake suite maintained and supported by Kitware (kitware.com/cmake).

**Comment by go2sh** [comment]
Ah interesting. The regex to check looks like `cmake version (\d+\.\d+\.\d+)`. So your version output falls through. Did not realize, that distributions change the name of the executable to `cmake3`. Will fix that with the next release.
