### ISSUE TITLE
toolchain option not working properly

### ISSUE THREAD

**Issue by hjesuiter** [go2sh/cmake-integration-vscode#52]
Hi, 

The last update to 0.7.0 ignores the toolchain-setting, where I usually give a specific toolchain file to my cmake configurations. In 0.6.5 it works fine, so probably there are some changes there I'm not aware of. 

My setup: connect to a remote machine that hosts the projects code and does (cross-) builds. The project contains several CMAKE toolchain files depending on the target platform. My configuration looks like (multiple times for different platforms): 
{
      "name": "COMi.MX Debug",
      "buildType": "Debug",
      "buildDirectory": "${workspaceFolder}/build/comimx/${buildType}",
      "toolchain": "${workspaceFolder}/cmake/poky_toolchain-arm-imx.cmake",
      "cacheEntries": [
        {
          "name": "RV_RTP_FPGA_COMIMX",
          "value": "1",
          "type": "BOOL"
        },
        {
          "name": "RV_PTP",
          "value": "linuxptp",
          "type": "STRING"
        }
      ]
    },

While in 0.6.5 the toolchain file is properly found and used (settings für compiler, libraries and paths), in 0.7.0 this doesn't work anymore. Instead it tries to use the defaults (i.e. /usr/bin/cc instead of (crosstoolchain/architecture/cc). Do I have to update the config somewhere?

**Comment by hriekehof** [comment]
I should have read this first :) I have the same issue #53

**Comment by go2sh** [comment]
Ach mist. Sorry, i'll check it out tonight.
