### ISSUE TITLE
Build directory creation fails with EEXIST for new workspaces

### ISSUE THREAD

**Issue by tambry** [go2sh/cmake-integration-vscode#55]
I'm using remote SSH.

1. Create and open a new folder.
2. Create a simple CMake project (e.g. executable with one file)
3. F1→"CMake: Configure workspace"
4. A `build` directory is created in the workspace and an error appears: `Failed to configure project(<project_name>): EEXIST: file already exists, mkdir '<workspace>/build'`

Running the configure a second time or deleting the `build` folder and then configuring will successfully configure the project.

**Comment by go2sh** [comment]
Can reproduce it. Need to make some changes to fix it. There is a race condition between to mkdirs...
