### ISSUE TITLE
Feature Request: CMake Problem Matcher

### ISSUE THREAD

**Issue by atar-axis** [go2sh/cmake-integration-vscode#6]
Hi again,
another  useful feature would be a useful problem matcher for the CMake output ;)

Cheers,
Flo

**Comment by go2sh** [comment]
Hiho, 
ist ein der aktuellen beta4 drin. :-)
Gruß,
go2sh

**Comment by atar-axis** [comment]
Hola,... Another great Feature - Thank you so much!!
