### ISSUE TITLE
Add Intellisense support for header and unknown files

### ISSUE THREAD

**Issue by go2sh** [go2sh/cmake-integration-vscode#7]

**Comment by atar-axis** [comment]
While hitting <kbd>F12</kbd> the message "not found" appears - is that what this issue is about?

![image](https://user-images.githubusercontent.com/11148588/52452182-570fcd00-2b42-11e9-9cc5-3969224f80ed.png)
[cmake_integration_test.zip](https://github.com/go2sh/cmake-integration-vscode/files/2843196/cmake_integration_test.zip)

**Comment by go2sh** [comment]
This is a issue with the cpptools. I see the same. Try to open and close foo/bar.h and hit F12 again. The funny thing is. The types from the file get used correctly. So if you hit F12 on a class or function from that file, it  should be shown immediately. 

This issue is about getting the intellisense configuration for the header file it self. I'll release it in a moment.

**Comment by go2sh** [comment]
Just released it. :-)

**Comment by atar-axis** [comment]
> This is a issue with the cpptools.

Funny thing is: It does work when I disable CMake-Integration (and reset the database + reload).

**Comment by atar-axis** [comment]
![cmake_integration_not_found_issue](https://user-images.githubusercontent.com/11148588/52473811-0c6c7000-2b97-11e9-8b2d-ab1386158b9e.gif)

**Comment by go2sh** [comment]
can show me the content of the c_cpp_properties.json file?

**Comment by atar-axis** [comment]
For sure, see the .zip here: https://github.com/go2sh/cmake-integration-vscode/issues/7#issuecomment-461649633

(Or wait a Bit until i get to my pc)

**Comment by atar-axis** [comment]
```
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/src"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/g++",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "gcc-x64",
            "configurationProvider": "go2sh.cmake-integration"
        }
    ],
    "version": 4
}
```

**Comment by go2sh** [comment]
The thing is, your c_cpp_properties.json has `src` as include folder, where as your CMake project does not. This is the reason for your difference. I think it is some how a bug, that cpptools extension by default doesn't respect relative includes. :-/

**Comment by atar-axis** [comment]
Ha, you are right - after adding
```
target_include_directories(${PROJECT_NAME}
    PRIVATE
        src
)
```
everything works as expected. Thanks once again!
